version: '3'

services:
  worker:
    build: ./worker
    ports:
      - "8081:8080"

  worker_2:
    build: ./worker
    ports:
      - "8082:8080"

  worker_3:
    build: ./worker
    ports:
      - "8083:8080"

  worker_4:
    build: ./worker
    ports:
      - "8084:8080"

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "8080:80"
